### ISSUE TITLE
Missing https support

### ISSUE THREAD

**Issue by sergey-shambir** [cskr/gorepos#1]
I've added support in my fork: https://github.com/sergey-shambir/gorepos
I can create pull request if needed.

**Comment by cskr** [comment]
I run gorepos behind a reverse proxy which handles TLS termination. I am sure I am not alone in using it this way.

While it is certainly nice for gorepos to be able to handle TLS on its own, I don't want to mandate it for all users. Can you make TLS optional and then raise a PR?
